services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    autoDeploy: true

  - type: web
    name: react-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
